const commonTypes = {
  RESET_CURRENTS: "RESET_CURRENTS",
  IS_FETCHING: "IS_FETCHING",
  IS_FETCHED: "IS_FETCHED",
  SET_ERROR: "SET_ERROR",
  SET_IS_HEADER: "SET_IS_HEADER",
  SET_ALERTS: "SET_ALERTS",
  LOGOUT: "LOGOUT",
  RESET_SNACKBAR: "RESET_SNACKBAR",
};

export default commonTypes;
