const transportistaType = {
  SET_ESPECIES_ANIMALES: "SET_ESPECIES_ANIMALES",
  SET_COLORES: "SET_COLORES",
  DELETE_REGISTRO_VIA_PUBLICA: "DELETE_REGISTRO_VIA_PUBLICA",
  SET_REGISTRO_VIA_PUBLICA: "SET_REGISTRO_VIA_PUBLICA",
  SET_ERROR_DB_VIA_PUBLICA: "SET_ERROR_DB_VIA_PUBLICA",
  SET_CURRENT_REGISTRO_VIA_PUBLICA: "SET_CURRENT_REGISTRO_VIA_PUBLICA",
  SET_IS_FETCHING_REGISTRO_VIA_PUBLICA: "SET_IS_FETCHING_REGISTRO_VIA_PUBLICA",
};

export default transportistaType;
