const pescaTypeActions = {
    SET_PESCA_VALUES_START: 'SET_PESCA_VALUES_START',
    SET_PESCA_VALUES_SUCCESS: 'SET_PESCA_VALUES_SUCCESS',
    FETCH_PESCA_START:'FETCH_PESCA_START',
    FETCH_PESCA_SUCCESS: 'FETCH_PESCA_SUCCESS',
    FETCH_PESCAS_START: 'FETCH_PESCAS_START',
    FETCH_PESCAS_SUCCESS: 'FETCH_PESCAS_SUCCESS',
    DELETE_PESCA_START: 'DELETE_PESCA_START',
    DELETE_PESCA_SUCCESS: 'DELETE_PESCA_SUCCESS',
    SET_PESCA_ERROR:'SET_PESCA_ERROR',
};

export default pescaTypeActions;