const mergeTypeActions = {
    MERGE_USERS_AGENTES_START:'MERGE_USERS_AGENTES_START',
    MERGE_USERS_AGENTES_SUCCESS:'MERGE_USERS_AGENTES_SUCCESS',
    FIND_USER_AGENTE:'FIND_USER_AGENTE',
    FETCH_USERS_AGENTES_START: 'FETCH_USERS_AGENTES_START',
    FETCH_USERS_AGENTES_SUCCESS: 'FETCH_USERS_AGENTES_SUCCESS',
    FETCH_USER_AGENTE_START: 'FETCH_USER_AGENTE_START',
    FETCH_USER_AGENTE_SUCCESS:'FETCH_USER_AGENTE_SUCCESS',
    DELETE_USER_AGENTE_START:'DELETE_USER_AGENTE_START',
    DELETE_USER_AGENTE_SUCCESS:'DELETE_USER_AGENTE_SUCCESS',
    SET_CURRENT_USER_AGENTE: 'SET_CURRENT_USER_AGENTE',
    EDIT_USER_AGENTE_START:'EDIT_USER_AGENTE_START',
    EDIT_USER_AGENTE_SUCCESS:'EDIT_USER_AGENTE_SUCCESS'
};

export default mergeTypeActions;