const transportistasJSon=[
    {
      "Marca temporal": "25/1/2021 8:18:29",
      "CUIL - CUIT": "20-24104559-6",
      "Apellido y Nombre": "MONJE ALBERTO ISMAEL",
      "Domicilio": "BARRIO SOLIDARIDAD CASA Nº 40",
      "Telefono": "",
      "Localidad": "LAS FLORES",
      "Tipo de Alimentos a Transportar": "POLLO",
      "Dominio": "MOM703",
      "Marca": "RENAULT",
      "Modelo Año": "NUEVO MASTER 2013",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-178679 CAT A",
      "Vencimiento": "5/10/2021",
      "Empresa": "MONJE"
    },
    {
      "Marca temporal": "26/1/2021 7:06:55",
      "CUIL - CUIT": "20-21442163-2",
      "Apellido y Nombre": "VIGLIERI JORGE FABIAN",
      "Domicilio": "25 DE MAYO 1019",
      "Telefono": "",
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "FIAMBRES-QUESOS-PASTAS-SECOS",
      "Dominio": "JLE563",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "710    2010",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-320444 CAT A",
      "Vencimiento": "21/1/2022",
      "Empresa": "VIGLIERI"
    },
    {
      "Marca temporal": "26/1/2021 8:49:10",
      "CUIL - CUIT": "30-71504431-1",
      "Apellido y Nombre": "CABRAL OMAR WALTER Y CABRAL NORBERTO",
      "Domicilio": "AV. SAN MARTIN 435",
      "Telefono": "",
      "Localidad": "ABBOTT-MONTE",
      "Tipo de Alimentos a Transportar": "QUESOS (MUZZARELLA)",
      "Dominio": "AA015YP",
      "Marca": "RENAULT",
      "Modelo Año": "KANGOO PH3   2016",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-209979 CAT A",
      "Vencimiento": "7/1/2022",
      "Empresa": "CABRAL OMAR WALTER Y CABRAL NORBERTO"
    },
    {
      "Marca temporal": "27/1/2021 3:34:36",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "DISTRIBUIDORA FILARDO S.H.",
      "Domicilio": "MARCELO T DE ALVEAR 3445",
      "Telefono": 2344453393,
      "Localidad": "SALADILLO",
      "Tipo de Alimentos a Transportar": "LÁCTEOS, PRODUCTOS DE DESPENSA",
      "Dominio": "JHF046",
      "Marca": "DFM",
      "Modelo Año": "DUOLICA 1063CJ10    2010",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-326746 CAT A",
      "Vencimiento": "7/5/2021",
      "Empresa": "DISTRIBUIDORA FILARDO S.H."
    },
    {
      "Marca temporal": "27/1/2021 4:02:32",
      "CUIL - CUIT": "30-58888098-9",
      "Apellido y Nombre": "DAEDAZ S.A.",
      "Domicilio": "AVDA BUZON 372",
      "Telefono": 2494429099,
      "Localidad": "TANDIL",
      "Tipo de Alimentos a Transportar": "PRODUCTOS DE DESPENSA",
      "Dominio": "FHN198",
      "Marca": "FORD",
      "Modelo Año": "CARGO 1317 CHASIS CON CABINA 2013",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-44539 CAT A",
      "Vencimiento": "3/12/2021",
      "Empresa": "DAEDAZ S.A."
    },
    {
      "Marca temporal": "27/1/2021 4:08:56",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "IANNI ARIEL FERNANDO",
      "Domicilio": "AVDA CENTENARIO 1352",
      "Telefono": 2266431275,
      "Localidad": "BALCARCE",
      "Tipo de Alimentos a Transportar": "PANIFICADOS",
      "Dominio": "HRV636",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "SPRINTER 413",
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "2-53258 CAT C",
      "Vencimiento": "17/9/2021",
      "Empresa": "EL EDEN"
    },
    {
      "Marca temporal": "10/2/2021 7:58:59",
      "CUIL - CUIT": "27-16477311-1",
      "Apellido y Nombre": "MARIN MARIA DE LOS ANGELES",
      "Domicilio": "CALLE 253 Nº 445",
      "Telefono": "",
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "PASTAS, PANIFICADOS",
      "Dominio": "WMB069",
      "Marca": "FORD",
      "Modelo Año": "250 FURGON  1976",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-23798  CAT A",
      "Vencimiento": "15/9/2021",
      "Empresa": "DISTRIBUIDORA 7 DE ENERO"
    },
    {
      "Marca temporal": "10/2/2021 8:32:29",
      "CUIL - CUIT": "20-12093997-2",
      "Apellido y Nombre": "LOMBARDO GABRIEL ARMANDO",
      "Domicilio": "BOLIVAR 2782",
      "Telefono": "",
      "Localidad": "LOMAS DEL MIRADOR - LA MATANZA",
      "Tipo de Alimentos a Transportar": "PANIFICADOS",
      "Dominio": "ISP218",
      "Marca": "FIAT",
      "Modelo Año": "FIORINO",
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "2-269705  CAT C",
      "Vencimiento": "3/6/2021",
      "Empresa": "LA PERLA"
    },
    {
      "Marca temporal": "10/2/2021 8:59:09",
      "CUIL - CUIT": "-21554714-",
      "Apellido y Nombre": "FONTANA CONSTANZA",
      "Domicilio": "CASEROS 1276",
      "Telefono": "",
      "Localidad": "CAPITÁN SARMIENTO",
      "Tipo de Alimentos a Transportar": "POLLO",
      "Dominio": "EQR438",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "MAOLO 16/20   2012",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-   CAT A",
      "Vencimiento": "6/5/2021",
      "Empresa": "GRANJA TRES ARROYOS"
    },
    {
      "Marca temporal": "12/2/2021 8:33:21",
      "CUIL - CUIT": "27-23573086-9",
      "Apellido y Nombre": "BIUDES ALEJANDRA VIVIANA",
      "Domicilio": "CHARRUA 1688",
      "Telefono": "",
      "Localidad": "VILLA SANTOS TESEI - HURLINGHAM",
      "Tipo de Alimentos a Transportar": "Refrigerados, Carne vacuna, Fiambres, Hamburguesas",
      "Dominio": "AB293YL",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "ACCELO  2016",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-242476  CAT A",
      "Vencimiento": "25/6/2021",
      "Empresa": "DIA %"
    },
    {
      "Marca temporal": "12/2/2021 8:47:28",
      "CUIL - CUIT": "-11945697-",
      "Apellido y Nombre": "ZABALO LUIS RAMON",
      "Domicilio": "BELGRANO 555",
      "Telefono": "",
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "FIAMBRES, PANIFICADOS",
      "Dominio": "RLS484",
      "Marca": "FORD",
      "Modelo Año": "F350D",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2- CAT A",
      "Vencimiento": "25/1/2022",
      "Empresa": "DISTRIBUIDORA ZABALO"
    },
    {
      "Marca temporal": "17/2/2021 5:24:02",
      "CUIL - CUIT": "30-70015052-2",
      "Apellido y Nombre": "FABRICAS UNIDAS S.R.L. - VILLANO LEANDRO-ZURITA DARIO",
      "Domicilio": "PELLEGRINI 268",
      "Telefono": 1133871705,
      "Localidad": "PARANA - ENTRE RIOS",
      "Tipo de Alimentos a Transportar": "LÁCTEOS",
      "Dominio": "LTQ352",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "ACCELO 915C",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-280202  CAT A",
      "Vencimiento": "20/8/2021",
      "Empresa": "APYMEL-ALIMENTOS BONAERENSES"
    },
    {
      "Marca temporal": "17/2/2021 5:58:08",
      "CUIL - CUIT": "20-13689542-8",
      "Apellido y Nombre": "RODRIGUEZ ALBERTO JOSE",
      "Domicilio": "BLAQUIER 305",
      "Telefono": "",
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "PANIFICADOS",
      "Dominio": "JXG611",
      "Marca": "RENAULT",
      "Modelo Año": "MASTER PH3 DCI 120   2011",
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "2-336112   CAT C",
      "Vencimiento": "25/8/2021",
      "Empresa": "LA SALTEÑA"
    },
    {
      "Marca temporal": "17/2/2021 6:10:52",
      "CUIL - CUIT": "23-33912706-9",
      "Apellido y Nombre": "GOPAR AGUSTIN ALBERTO",
      "Domicilio": "JUNCAL 2945",
      "Telefono": "",
      "Localidad": "MAR DEL PLATA-GENERAL PUEYRREDON",
      "Tipo de Alimentos a Transportar": "REFRIGERADOS, FIAMBRES, LACTEOS",
      "Dominio": "VRJ353",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "1114    1974",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-305602   CAT A",
      "Vencimiento": "11/8/2021",
      "Empresa": "ECONOMIA POPULAR MOVIMIENTO EVITA"
    },
    {
      "Marca temporal": "17/2/2021 6:18:51",
      "CUIL - CUIT": "-30633779-",
      "Apellido y Nombre": "DE LA TORRE HECTOR DANIEL",
      "Domicilio": "BARRIO EMPLEADOS DE COMERCIO CASA Nº 25",
      "Telefono": 2244503125,
      "Localidad": "LAS FLORES",
      "Tipo de Alimentos a Transportar": "PANIFICADOS",
      "Dominio": "UV352",
      "Marca": "RENAULT",
      "Modelo Año": "TIPO TRAFIC   1987",
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "HABILITACION MUNICIPAL LAS FLORES",
      "Vencimiento": "28/2/2021",
      "Empresa": "DE LA TORRE HECTOR DANIEL"
    },
    {
      "Marca temporal": "17/2/2021 6:23:40",
      "CUIL - CUIT": "23-16731394-9",
      "Apellido y Nombre": "SIELAS GUSTAVO OMAR",
      "Domicilio": "AVELLANEDA 956",
      "Telefono": "",
      "Localidad": "LAS FLORES",
      "Tipo de Alimentos a Transportar": "LÁCTEOS",
      "Dominio": "AB110JM",
      "Marca": "IVECO",
      "Modelo Año": "DAILY 70C17  2017",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-245290  CAT A",
      "Vencimiento": "30/11/2021",
      "Empresa": "SANCOR"
    },
    {
      "Marca temporal": "17/2/2021 6:39:25",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "BELTRAN FRANCISCO",
      "Domicilio": "AZUL",
      "Telefono": "",
      "Localidad": "AZUL",
      "Tipo de Alimentos a Transportar": "PRODUCTOS DE DESPENSA",
      "Dominio": "AC063UB",
      "Marca": "IVECO",
      "Modelo Año": 2017,
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "HABILITACIÓN MUNICIPAL DE AZUL",
      "Vencimiento": "",
      "Empresa": "DISTRIBUIDORA REAL"
    },
    {
      "Marca temporal": "17/2/2021 7:08:46",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "GALLI JORGE OMAR",
      "Domicilio": "",
      "Telefono": "",
      "Localidad": "MONTE",
      "Tipo de Alimentos a Transportar": "Fiambres, Lácteos, Quesos",
      "Dominio": "AD227LH",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": 2018,
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2- CAT",
      "Vencimiento": "3/12/2021",
      "Empresa": "MAYOL"
    },
    {
      "Marca temporal": "17/2/2021 7:16:24",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "GABRIELLI FACUNDO",
      "Domicilio": "",
      "Telefono": "",
      "Localidad": "",
      "Tipo de Alimentos a Transportar": "HELADOS",
      "Dominio": "AC046KN",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": 2426,
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-  CAT A",
      "Vencimiento": "4/2/2021",
      "Empresa": "HELACOR"
    },
    {
      "Marca temporal": "17/2/2021 7:21:53",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "BACO SHOPS S.R.L.",
      "Domicilio": "",
      "Telefono": "",
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "BEBIDAS-SNACKS-FIDEOS",
      "Dominio": "AB656QD",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": 2017,
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "HABILITACION MUNICIPAL DE LOBOS",
      "Vencimiento": "16/9/2021",
      "Empresa": "DISTRIBUIDORA BABILONIA"
    },
    {
      "Marca temporal": "19/2/2021 8:51:55",
      "CUIL - CUIT": "30-51730709-9",
      "Apellido y Nombre": "GRANJA TRES ARROYOS SOCIEDAD",
      "Domicilio": "TRES ARROYOS 378",
      "Telefono": "",
      "Localidad": "CABA",
      "Tipo de Alimentos a Transportar": "POLLO",
      "Dominio": "IUC079",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "L 1624   2010",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-36534   CAT A",
      "Vencimiento": "13/8/2021",
      "Empresa": "GRANJA TRES ARROYOS"
    },
    {
      "Marca temporal": "2/3/2021 5:39:54",
      "CUIL - CUIT": "30-58888098-9",
      "Apellido y Nombre": "DAEDAZ S.A.",
      "Domicilio": "AVDA BUZON 372",
      "Telefono": 2494429099,
      "Localidad": "TANDIL",
      "Tipo de Alimentos a Transportar": "PRODUCTOS DE DESPENSA",
      "Dominio": "AE338BV",
      "Marca": "170E28NCM51",
      "Modelo Año": "IVECO   2020",
      "Equipo de Frio": "NO",
      "Nro. Habilitación SENASA": "2-352493   CAT B",
      "Vencimiento": "28/1/2022",
      "Empresa": "DAEDAZ S.A."
    },
    {
      "Marca temporal": "2/3/2021 6:09:57",
      "CUIL - CUIT": "20-18414913-4",
      "Apellido y Nombre": "RUGGERI GUSTAVO GABRIEL",
      "Domicilio": "STROBEL 4321",
      "Telefono": "",
      "Localidad": "MAR DEL PLATA-GENERAL PUEYRREDON",
      "Tipo de Alimentos a Transportar": "PESCADO",
      "Dominio": "LZF358",
      "Marca": "IVECO",
      "Modelo Año": "DAILY 70C16 PASO  2012",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-315812   CAT A",
      "Vencimiento": "13/11/2021",
      "Empresa": "GEMMA PESCADOS"
    },
    {
      "Marca temporal": "4/3/2021 4:51:23",
      "CUIL - CUIT": "",
      "Apellido y Nombre": "BELARDINELLI OMAR CLEMENTE",
      "Domicilio": "BERRO 291",
      "Telefono": "",
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "REFRIGERADOS, PRODUCTOS DE DESPENSA",
      "Dominio": "HQK136",
      "Marca": "MERCEDES BENZ",
      "Modelo Año": "PICK UP SPRINTER   2009",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "MUNICIPALIDAD DE LOBOS Nº 1021",
      "Vencimiento": "18/11/2021",
      "Empresa": "BELARDINELLI"
    },
    {
      "Marca temporal": "15/3/2021 5:15:40",
      "CUIL - CUIT": "30-70870312-0",
      "Apellido y Nombre": "LACTEOS DEL SALADO S.R.L.",
      "Domicilio": "ALEM LN 61 PISO 8 DTO 20",
      "Telefono": "",
      "Localidad": "CABA",
      "Tipo de Alimentos a Transportar": "LACTEOS",
      "Dominio": "NLR326",
      "Marca": "FIAT IVECO",
      "Modelo Año": "VERTIS 130 V18   2014",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-350845  CAT A",
      "Vencimiento": "7/1/2022",
      "Empresa": "LACTEOS DEL SALADO S.R.L."
    },
    {
      "Marca temporal": "26/1/2021 8:28:29",
      "CUIL - CUIT": "20-13948749-5",
      "Apellido y Nombre": "BURGOS HORACIO",
      "Domicilio": "BLAQUIER 705",
      "Telefono": 2227521900,
      "Localidad": "LOBOS",
      "Tipo de Alimentos a Transportar": "CARNE VACUNA, PORCINA, POLLO Y MENUDENCIAS",
      "Dominio": "AA046XC",
      "Marca": "FIAT",
      "Modelo Año": "IVECO 2016",
      "Equipo de Frio": "SI",
      "Nro. Habilitación SENASA": "2-215616 CAT A",
      "Vencimiento": "14/7/2021",
      "Empresa": "BURGOS"
    }
  ]
  module.exports = transportistasJSon;