const localidades =["LAS FLORES","LOBOS","ABBOTT-MONTE","SALADILLO","TANDIL","BALCARCE","LOMAS DEL MIRADOR - LA MATANZA","CAPITÁN SARMIENTO","VILLA SANTOS TESEI - HURLINGHAM","PARANA - ENTRE RIOS","MAR DEL PLATA-GENERAL PUEYRREDON","AZUL","MONTE","CABA"]

module.exports = localidades;