const agenteTypeActions = {
    SET_AGENTE_SUCCESS: 'SET_AGENTE_SUCCESS',
    SET_AGENTE_VALUES_START: 'SET_AGENTE_VALUES_START',
    SET_AGENTE_VALUES_SUCCESS: 'SET_AGENTE_VALUES_SUCCESS',
    FETCH_AGENTES_START: 'FETCH_AGENTES_START',
    FETCH_AGENTES_SUCCESS: 'FETCH_AGENTES_SUCCESS',
    RESET_CURRENTS: 'RESET_CURRENTS',
    FETCH_AGENTE_START: 'FETCH_AGENTE_START',
    FETCH_AGENTE_SUCCESS: 'FETCH_AGENTE_SUCCESS',
    DELETE_AGENTE_START: 'DELETE_AGENTE_START',
    DELETE_AGENTE_SUCCESS: 'DELETE_AGENTE_SUCCESS',
    SET_AGENTE_ERROR: 'SET_AGENTE_ERROR',
};

export default agenteTypeActions;