const bromatologiaType = {
  SET_PERMISO_BROMATOLOGIA: "SET_PERMISO_BROMATOLOGIA",
  SET_PERMISOS_BROMATOLOGIA:"SET_PERMISOS_BROMATOLOGIA",
  SET_CURRENT_PERMISO: "SET_CURRENT_PERMISO",
  SET_RUBRO: "SET_RUBRO",
  SET_NOMBRE_COMERCIAL: "SET_NOMBRE_COMERCIAL",
  SET_RAZON_SOCIAL: "SET_RAZON_SOCIAL",
  DELETE_PERMISO: "DELETE_PERMISO",
  SET_IS_FETCHING_BROMATOLOGIA:"SET_IS_FETCHING_BROMATOLOGIA",
  SET_ERROR_DB:"SET_ERROR_DB"
};

export default bromatologiaType;
