const userTypeActions = {
    FETCH_USERS_START: 'FETCH_USERS_START',    
    FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS : 'FETCH_USER_SUCCESS',
    SET_USER_START:'SET_USER_START',
    SET_USER_SUCCESS:'SET_USER_SUCCESS',
    DELETE_USER_START:'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    SET_ADMIN_START:'SET_ADMIN_START',
    SET_ADMIN_SUCCESS:'SET_ADMIN_SUCCESS',
    SET_CURRENT_IMG : 'SET_CURRENT_IMG',
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    DELETE_USER : 'DELETE_USER',
    IS_GENERATED : 'IS_GENERATED',
    FIND_USER : 'FIND_USER',    
    SET_TOGGLE_IMG : 'SET_TOGGLE_IMG',
    SET_USER_ERROR: 'SET_USER_ERROR'
};

export default userTypeActions;

