const transportistaType = {
  SET_LOCALIDADES:"SET_LOCALIDADES",
  SET_TIPO_ALIMENTOS_TRANSPORTAR:"SET_TIPO_ALIMENTOS_TRANSPORTAR",
  SET_EMPRESAS:"SET_EMPRESAS",
  SET_REGISTRO_TRANSPORTISTA:"SET_REGISTRO_TRANSPORTISTA",
  SET_CURRENT_REGISTRO:"SET_CURRENT_REGISTRO",
  DELETE_REGISTRO:"DELETE_REGISTRO",
  SET_ERROR_DB_TRANSPORTE:"SET_ERROR_DB_TRANSPORTE",
  SET_IS_FETCHING_TRANSPORTE:"SET_IS_FETCHING_TRANSPORTE",
  SET_PERMISOS_TRANSPORTE:"SET_PERMISOS_TRANSPORTE"
};

export default transportistaType;
