export const dataRegistros = {
  MONJE: {
    valuesForm: { empresa: "MONJE" },
    vehiculos: [
      {
        cuilCuit: "20-24104559-6",
        apellidoYNombre: "MONJE ALBERTO ISMAEL",
        domicilio: "BARRIO SOLIDARIDAD CASA Nº 40",
        telefono: "",
        localidad: "LAS FLORES",
        tipoAlimentoTransportar: "POLLO",
        nroSenasa: "2-178679 CAT A",
        vencimiento: "Tue Oct 05 2021 00:00:00 GMT-0300",
        dominio: "MOM703",
        marca: "RENAULT",
        modeloAnio: "NUEVO MASTER 2013",
        equipoFrio: "SI",
      },
    ],
  },
  VIGLIERI: {
    valuesForm: { empresa: "VIGLIERI" },
    vehiculos: [
      {
        cuilCuit: "20-21442163-2",
        apellidoYNombre: "VIGLIERI JORGE FABIAN",
        domicilio: "25 DE MAYO 1019",
        telefono: "",
        localidad: "LOBOS",
        tipoAlimentoTransportar: "FIAMBRES-QUESOS-PASTAS-SECOS",
        dominio: "JLE563",
        marca: "MERCEDES BENZ",
        modeloAnio: "710    2010",
        equipoFrio: "SI",
        nroSenasa: "2-320444 CAT A",
        vencimiento: "Fri Jan 21 2022 00:00:00 GMT-0300",
      },
    ],
  },
  "CABRAL OMAR WALTER Y CABRAL NORBERTO": {
    valuesForm: { empresa: "CABRAL OMAR WALTER Y CABRAL NORBERTO" },
    vehiculos: [
      {
        cuilCuit: "30-71504431-1",
        apellidoYNombre: "CABRAL OMAR WALTER Y CABRAL NORBERTO",
        domicilio: "AV. SAN MARTIN 435",
        telefono: "",
        localidad: "ABBOTT-MONTE",
        tipoAlimentoTransportar: "QUESOS (MUZZARELLA)",
        dominio: "AA015YP",
        marca: "RENAULT",
        modeloAnio: "KANGOO PH3   2016",
        equipoFrio: "SI",
        nroSenasa: "2-209979 CAT A",
        vencimiento: "Fri Jan 07 2022 00:00:00 GMT-0300",
      },
    ],
  },
  "DISTRIBUIDORA FILARDO S.H.": {
    valuesForm: { empresa: "DISTRIBUIDORA FILARDO S.H." },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "DISTRIBUIDORA FILARDO S.H.",
        domicilio: "MARCELO T DE ALVEAR 3445",
        telefono: 2344453393,
        localidad: "SALADILLO",
        tipoAlimentoTransportar: "LÁCTEOS, PRODUCTOS DE DESPENSA",
        dominio: "JHF046",
        marca: "DFM",
        modeloAnio: "DUOLICA 1063CJ10    2010",
        equipoFrio: "SI",
        nroSenasa: "2-326746 CAT A",
        vencimiento: "Fri May 07 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DAEDAZ S.A.": {
    valuesForm: { empresa: "DAEDAZ S.A." },
    vehiculos: [
      {
        cuilCuit: "30-58888098-9",
        apellidoYNombre: "DAEDAZ S.A.",
        domicilio: "AVDA BUZON 372",
        telefono: 2494429099,
        localidad: "TANDIL",
        tipoAlimentoTransportar: "PRODUCTOS DE DESPENSA",
        dominio: "FHN198",
        marca: "FORD",
        modeloAnio: "CARGO 1317 CHASIS CON CABINA 2013",
        equipoFrio: "SI",
        nroSenasa: "2-44539 CAT A",
        vencimiento: "Fri Dec 03 2021 00:00:00 GMT-0300",
      },
      {
        cuilCuit: "30-58888098-9",
        apellidoYNombre: "DAEDAZ S.A.",
        domicilio: "AVDA BUZON 372",
        telefono: 2494429099,
        localidad: "TANDIL",
        tipoAlimentoTransportar: "PRODUCTOS DE DESPENSA",
        dominio: "AE338BV",
        marca: "170E28NCM51",
        modeloAnio: "IVECO   2020",
        equipoFrio: "NO",
        nroSenasa: "2-352493   CAT B",
        vencimiento: "Fri Jan 28 2022 00:00:00 GMT-0300",
      },
    ],
  },
  "EL EDEN": {
    valuesForm: { empresa: "EL EDEN" },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "IANNI ARIEL FERNANDO",
        domicilio: "AVDA CENTENARIO 1352",
        telefono: 2266431275,
        localidad: "BALCARCE",
        tipoAlimentoTransportar: "PANIFICADOS",
        dominio: "HRV636",
        marca: "MERCEDES BENZ",
        modeloAnio: "SPRINTER 413",
        equipoFrio: "NO",
        nroSenasa: "2-53258 CAT C",
        vencimiento: "Fri Sep 17 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DISTRIBUIDORA 7 DE ENERO": {
    valuesForm: { empresa: "DISTRIBUIDORA 7 DE ENERO" },
    vehiculos: [
      {
        cuilCuit: "27-16477311-1",
        apellidoYNombre: "MARIN MARIA DE LOS ANGELES",
        domicilio: "CALLE 253 Nº 445",
        telefono: "",
        localidad: "LOBOS",
        tipoAlimentoTransportar: "PASTAS, PANIFICADOS",
        dominio: "WMB069",
        marca: "FORD",
        modeloAnio: "250 FURGON  1976",
        equipoFrio: "SI",
        nroSenasa: "2-23798  CAT A",
        vencimiento: "Wed Sep 15 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "LA PERLA": {
    valuesForm: { empresa: "LA PERLA" },
    vehiculos: [
      {
        cuilCuit: "20-12093997-2",
        apellidoYNombre: "LOMBARDO GABRIEL ARMANDO",
        domicilio: "BOLIVAR 2782",
        telefono: "",
        localidad: "LOMAS DEL MIRADOR - LA MATANZA",
        tipoAlimentoTransportar: "PANIFICADOS",
        dominio: "ISP218",
        marca: "FIAT",
        modeloAnio: "FIORINO",
        equipoFrio: "NO",
        nroSenasa: "2-269705  CAT C",
        vencimiento: "Thu Jun 03 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "GRANJA TRES ARROYOS": {
    valuesForm: { empresa: "GRANJA TRES ARROYOS" },
    vehiculos: [
      {
        cuilCuit: "-21554714-",
        apellidoYNombre: "FONTANA CONSTANZA",
        domicilio: "CASEROS 1276",
        telefono: "",
        localidad: "CAPITÁN SARMIENTO",
        tipoAlimentoTransportar: "POLLO",
        dominio: "EQR438",
        marca: "MERCEDES BENZ",
        modeloAnio: "MAOLO 16/20   2012",
        equipoFrio: "SI",
        nroSenasa: "2-   CAT A",
        vencimiento: "Thu May 06 2021 00:00:00 GMT-0300",
      },
      {
        cuilCuit: "30-51730709-9",
        apellidoYNombre: "GRANJA TRES ARROYOS SOCIEDAD",
        domicilio: "TRES ARROYOS 378",
        telefono: "",
        localidad: "CABA",
        tipoAlimentoTransportar: "POLLO",
        dominio: "IUC079",
        marca: "MERCEDES BENZ",
        modeloAnio: "L 1624   2010",
        equipoFrio: "SI",
        nroSenasa: "2-36534   CAT A",
        vencimiento: "Fri Aug 13 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DIA %": {
    valuesForm: { empresa: "DIA %" },
    vehiculos: [
      {
        cuilCuit: "27-23573086-9",
        apellidoYNombre: "BIUDES ALEJANDRA VIVIANA",
        domicilio: "CHARRUA 1688",
        telefono: "",
        localidad: "VILLA SANTOS TESEI - HURLINGHAM",
        tipoAlimentoTransportar:
          "Refrigerados, Carne vacuna, Fiambres, Hamburguesas",
        dominio: "AB293YL",
        marca: "MERCEDES BENZ",
        modeloAnio: "ACCELO  2016",
        equipoFrio: "SI",
        nroSenasa: "2-242476  CAT A",
        vencimiento: "Fri Jun 25 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DISTRIBUIDORA ZABALO": {
    valuesForm: { empresa: "DISTRIBUIDORA ZABALO" },
    vehiculos: [
      {
        cuilCuit: "-11945697-",
        apellidoYNombre: "ZABALO LUIS RAMON",
        domicilio: "BELGRANO 555",
        telefono: "",
        localidad: "LOBOS",
        tipoAlimentoTransportar: "FIAMBRES, PANIFICADOS",
        dominio: "RLS484",
        marca: "FORD",
        modeloAnio: "F350D",
        equipoFrio: "SI",
        nroSenasa: "2- CAT A",
        vencimiento: "Tue Jan 25 2022 00:00:00 GMT-0300",
      },
    ],
  },
  "APYMEL-ALIMENTOS BONAERENSES": {
    valuesForm: { empresa: "APYMEL-ALIMENTOS BONAERENSES" },
    vehiculos: [
      {
        cuilCuit: "30-70015052-2",
        apellidoYNombre:
          "FABRICAS UNIDAS S.R.L. - VILLANO LEANDRO-ZURITA DARIO",
        domicilio: "PELLEGRINI 268",
        telefono: 1133871705,
        localidad: "PARANA - ENTRE RIOS",
        tipoAlimentoTransportar: "LÁCTEOS",
        dominio: "LTQ352",
        marca: "MERCEDES BENZ",
        modeloAnio: "ACCELO 915C",
        equipoFrio: "SI",
        nroSenasa: "2-280202  CAT A",
        vencimiento: "Fri Aug 20 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "LA SALTEÑA": {
    valuesForm: { empresa: "LA SALTEÑA" },
    vehiculos: [
      {
        cuilCuit: "20-13689542-8",
        apellidoYNombre: "RODRIGUEZ ALBERTO JOSE",
        domicilio: "BLAQUIER 305",
        telefono: "",
        localidad: "LOBOS",
        tipoAlimentoTransportar: "PANIFICADOS",
        dominio: "JXG611",
        marca: "RENAULT",
        modeloAnio: "MASTER PH3 DCI 120   2011",
        equipoFrio: "NO",
        nroSenasa: "2-336112   CAT C",
        vencimiento: "Wed Aug 25 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "ECONOMIA POPULAR MOVIMIENTO EVITA": {
    valuesForm: { empresa: "ECONOMIA POPULAR MOVIMIENTO EVITA" },
    vehiculos: [
      {
        cuilCuit: "23-33912706-9",
        apellidoYNombre: "GOPAR AGUSTIN ALBERTO",
        domicilio: "JUNCAL 2945",
        telefono: "",
        localidad: "MAR DEL PLATA-GENERAL PUEYRREDON",
        tipoAlimentoTransportar: "REFRIGERADOS, FIAMBRES, LACTEOS",
        dominio: "VRJ353",
        marca: "MERCEDES BENZ",
        modeloAnio: "1114    1974",
        equipoFrio: "SI",
        nroSenasa: "2-305602   CAT A",
        vencimiento: "Wed Aug 11 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DE LA TORRE HECTOR DANIEL": {
    valuesForm: { empresa: "DE LA TORRE HECTOR DANIEL" },
    vehiculos: [
      {
        cuilCuit: "-30633779-",
        apellidoYNombre: "DE LA TORRE HECTOR DANIEL",
        domicilio: "BARRIO EMPLEADOS DE COMERCIO CASA Nº 25",
        telefono: 2244503125,
        localidad: "LAS FLORES",
        tipoAlimentoTransportar: "PANIFICADOS",
        dominio: "UV352",
        marca: "RENAULT",
        modeloAnio: "TIPO TRAFIC   1987",
        equipoFrio: "NO",
        nroSenasa: "HABILITACION MUNICIPAL LAS FLORES",
        vencimiento: "Sun Feb 28 2021 00:00:00 GMT-0300",
      },
    ],
  },
  SANCOR: {
    valuesForm: { empresa: "SANCOR" },
    vehiculos: [
      {
        cuilCuit: "23-16731394-9",
        apellidoYNombre: "SIELAS GUSTAVO OMAR",
        domicilio: "AVELLANEDA 956",
        telefono: "",
        localidad: "LAS FLORES",
        tipoAlimentoTransportar: "LÁCTEOS",
        dominio: "AB110JM",
        marca: "IVECO",
        modeloAnio: "DAILY 70C17  2017",
        equipoFrio: "SI",
        nroSenasa: "2-245290  CAT A",
        vencimiento: "Tue Nov 30 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DISTRIBUIDORA REAL": {
    valuesForm: { empresa: "DISTRIBUIDORA REAL" },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "BELTRAN FRANCISCO",
        domicilio: "AZUL",
        telefono: "",
        localidad: "AZUL",
        tipoAlimentoTransportar: "PRODUCTOS DE DESPENSA",
        dominio: "AC063UB",
        marca: "IVECO",
        modeloAnio: 2017,
        equipoFrio: "NO",
        nroSenasa: "HABILITACIÓN MUNICIPAL DE AZUL",
        vencimiento: "Invalid date",
      },
    ],
  },
  MAYOL: {
    valuesForm: { empresa: "MAYOL" },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "GALLI JORGE OMAR",
        domicilio: "",
        telefono: "",
        localidad: "MONTE",
        tipoAlimentoTransportar: "Fiambres, Lácteos, Quesos",
        dominio: "AD227LH",
        marca: "MERCEDES BENZ",
        modeloAnio: 2018,
        equipoFrio: "SI",
        nroSenasa: "2- CAT",
        vencimiento: "Fri Dec 03 2021 00:00:00 GMT-0300",
      },
    ],
  },
  HELACOR: {
    valuesForm: { empresa: "HELACOR" },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "GABRIELLI FACUNDO",
        domicilio: "",
        telefono: "",
        localidad: "",
        tipoAlimentoTransportar: "HELADOS",
        dominio: "AC046KN",
        marca: "MERCEDES BENZ",
        modeloAnio: 2426,
        equipoFrio: "SI",
        nroSenasa: "2-  CAT A",
        vencimiento: "Thu Feb 04 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "DISTRIBUIDORA BABILONIA": {
    valuesForm: { empresa: "DISTRIBUIDORA BABILONIA" },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "BACO SHOPS S.R.L.",
        domicilio: "",
        telefono: "",
        localidad: "LOBOS",
        tipoAlimentoTransportar: "BEBIDAS-SNACKS-FIDEOS",
        dominio: "AB656QD",
        marca: "MERCEDES BENZ",
        modeloAnio: 2017,
        equipoFrio: "NO",
        nroSenasa: "HABILITACION MUNICIPAL DE LOBOS",
        vencimiento: "Thu Sep 16 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "GEMMA PESCADOS": {
    valuesForm: { empresa: "GEMMA PESCADOS" },
    vehiculos: [
      {
        cuilCuit: "20-18414913-4",
        apellidoYNombre: "RUGGERI GUSTAVO GABRIEL",
        domicilio: "STROBEL 4321",
        telefono: "",
        localidad: "MAR DEL PLATA-GENERAL PUEYRREDON",
        tipoAlimentoTransportar: "PESCADO",
        dominio: "LZF358",
        marca: "IVECO",
        modeloAnio: "DAILY 70C16 PASO  2012",
        equipoFrio: "SI",
        nroSenasa: "2-315812   CAT A",
        vencimiento: "Sat Nov 13 2021 00:00:00 GMT-0300",
      },
    ],
  },
  BELARDINELLI: {
    valuesForm: { empresa: "BELARDINELLI" },
    vehiculos: [
      {
        cuilCuit: "",
        apellidoYNombre: "BELARDINELLI OMAR CLEMENTE",
        domicilio: "BERRO 291",
        telefono: "",
        localidad: "LOBOS",
        tipoAlimentoTransportar: "REFRIGERADOS, PRODUCTOS DE DESPENSA",
        dominio: "HQK136",
        marca: "MERCEDES BENZ",
        modeloAnio: "PICK UP SPRINTER   2009",
        equipoFrio: "SI",
        nroSenasa: "MUNICIPALIDAD DE LOBOS Nº 1021",
        vencimiento: "Thu Nov 18 2021 00:00:00 GMT-0300",
      },
    ],
  },
  "LACTEOS DEL SALADO S.R.L.": {
    valuesForm: { empresa: "LACTEOS DEL SALADO S.R.L." },
    vehiculos: [
      {
        cuilCuit: "30-70870312-0",
        apellidoYNombre: "LACTEOS DEL SALADO S.R.L.",
        domicilio: "ALEM LN 61 PISO 8 DTO 20",
        telefono: "",
        localidad: "CABA",
        tipoAlimentoTransportar: "LACTEOS",
        dominio: "NLR326",
        marca: "FIAT IVECO",
        modeloAnio: "VERTIS 130 V18   2014",
        equipoFrio: "SI",
        nroSenasa: "2-350845  CAT A",
        vencimiento: "Fri Jan 07 2022 00:00:00 GMT-0300",
      },
    ],
  },
  BURGOS: {
    valuesForm: { empresa: "BURGOS" },
    vehiculos: [
      {
        cuilCuit: "20-13948749-5",
        apellidoYNombre: "BURGOS HORACIO",
        domicilio: "BLAQUIER 705",
        telefono: 2227521900,
        localidad: "LOBOS",
        tipoAlimentoTransportar: "CARNE VACUNA, PORCINA, POLLO Y MENUDENCIAS",
        dominio: "AA046XC",
        marca: "FIAT",
        modeloAnio: "IVECO 2016",
        equipoFrio: "SI",
        nroSenasa: "2-215616 CAT A",
        vencimiento: "Wed Jul 14 2021 00:00:00 GMT-0300",
      },
    ],
  },
};
